// flow-typed signature: 4f4cb382b410fbd42802c51ea82f2386
// flow-typed version: <<STUB>>/babili_v0.1.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babili'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babili' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babili/bin/babili' {
  declare module.exports: any;
}

declare module 'babili/lib/cli' {
  declare module.exports: any;
}

declare module 'babili/lib/fs' {
  declare module.exports: any;
}

declare module 'babili/lib/index' {
  declare module.exports: any;
}

declare module 'babili/lib/options-parser' {
  declare module.exports: any;
}

declare module 'babili/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babili/bin/babili.js' {
  declare module.exports: $Exports<'babili/bin/babili'>;
}
declare module 'babili/lib/cli.js' {
  declare module.exports: $Exports<'babili/lib/cli'>;
}
declare module 'babili/lib/fs.js' {
  declare module.exports: $Exports<'babili/lib/fs'>;
}
declare module 'babili/lib/index.js' {
  declare module.exports: $Exports<'babili/lib/index'>;
}
declare module 'babili/lib/options-parser.js' {
  declare module.exports: $Exports<'babili/lib/options-parser'>;
}
declare module 'babili/src/index.js' {
  declare module.exports: $Exports<'babili/src/index'>;
}
